apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: poscafe
resources:
  - namespace.yaml
  - configmap.yaml
  - migration-job.yaml
  - gateway.yaml
  - apis.yaml
  - network-policy.yaml
