apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: poscafe-default-deny
spec:
  podSelector: {}
  policyTypes: [Ingress, Egress]
  egress:
    - to:
        - namespaceSelector: { matchLabels: { kubernetes.io/metadata.name: kube-system } }
      ports:
        - { protocol: UDP, port: 53 }
        - { protocol: TCP, port: 53 }
    - to:
        - namespaceSelector: { matchLabels: { app.kubernetes.io/part-of: poscafe } }
      ports:
        - { protocol: TCP, port: 5432 }
        - { protocol: TCP, port: 27017 }
        - { protocol: TCP, port: 9092 }
  ingress:
    - from:
        - namespaceSelector: { matchLabels: { kubernetes.io/metadata.name: poscafe } }
      ports: [{ protocol: TCP, port: 8080 }]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: poscafe-gateway-ingress
spec:
  podSelector: { matchLabels: { app: poscafe-gateway } }
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector: { matchLabels: { kubernetes.io/metadata.name: ingress-nginx } }
      ports: [{ protocol: TCP, port: 8080 }]
