<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.5.3" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PosCafe.Catalog.Application\PosCafe.Catalog.Application.csproj" />
    <ProjectReference Include="..\PosCafe.Catalog.Infrastructure\PosCafe.Catalog.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\PosCafe.ServiceDefaults\PosCafe.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
